### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'values'

### ISSUE THREAD

**Issue by avnerkantor** [hrossman/corona-critical-cases-model-weizmann#1]

**Comment by hrossman** [comment]
Hi, did u try running the notebook and get this (i.e. using the data.csv format and inputs)? Or from a the function itself?
Anyway, I pushed something that may fix this

**Comment by avnerkantor** [comment]
Hi, I run the notebook. Now it works. Thanks!
